version: '3.8'

services:
  database:
    image: postgres:latest
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-network

  pgadmin:
    depends_on:
      - database
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8081:80"
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
    networks:
      - spring-network

volumes:
  db-data:

networks:
  spring-network:
    driver: bridge
